# Site settings
name: Dishant Rathi
title: Dishant Rathi | 20, Freelancer Web Designer & Developer, Techno Geek & Blog Writer. Founder of The Computerist. He is a Programmer, Photography & Music Lover, Hacktivist, Author, Geeky about Technology Stuff.
description:  20, Freelancer Web Designer & Developer, Techno Geek & Blog Writer. Founder of The Computerist. He is a Programmer, Photography & Music Lover, Hacktivist, Author, Geeky about Technology Stuff.
url: http://dishantrathi.tk/
baseurl: ""
email: dishantrathi97@gmail.com
cover: http://dishantrathi.tk/img/og.png
logo: http://dishantrathi.tk/img/emojis/technologist.png
resume: http://dishantrathi.tk/
social:
  - title: email
    url: mailto:dishantrathi97@gmail.com
  - title: medium
    url: https://medium.com/@dishantrathi
  - title: twitter
    url: https://twitter.com/techiedishant
  - title: instagram
    url: https://instagram.com/rathidishant
  - title: github
    url: https://github.com/dishantrathi
  - title: linkedin
    url: https://www.linkedin.com/in/dishantrathi

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
